import os
import csv
import json
import datetime
from sqlalchemy.orm import Session
from fpdf import FPDF
from .models import Device, Incident, SimulationState, TelemetryRun

REPORTS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "reports"))
os.makedirs(REPORTS_DIR, exist_ok=True)

class NetSagePDF(FPDF):
    def header(self):
        # Header banner
        self.set_fill_color(15, 23, 42) # Deep Slate Blue
        self.rect(0, 0, 210, 40, "F")
        
        self.set_text_color(255, 255, 255)
        self.set_font("helvetica", "B", 24)
        self.cell(0, 10, "NETSAGE", align="L", ln=True)
        self.set_font("helvetica", "I", 10)
        self.cell(0, 5, "AI-Powered Network Assurance & Diagnostics", align="L", ln=True)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by NetSage Diagnostics on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", align="C")

def generate_pdf_report(db: Session) -> str:
    pdf = NetSagePDF()
    pdf.add_page()
    pdf.set_y(45)
    
    # Title
    pdf.set_text_color(15, 23, 42)
    pdf.set_font("helvetica", "B", 18)
    pdf.cell(0, 10, "Network Health & Troubleshooting Assessment", ln=True)
    pdf.ln(5)
    
    # Executive Summary Section
    pdf.set_fill_color(241, 245, 249)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, " 1. Executive Summary", fill=True, ln=True)
    pdf.ln(2)
    
    # Fetch database metrics
    devices = db.query(Device).all()
    total_devices = len(devices)
    healthy_devices = len([d for d in devices if d.status == "Healthy"])
    critical_devices = len([d for d in devices if d.status == "Critical"])
    
    open_incidents = db.query(Incident).filter(Incident.status == "Open").all()
    resolved_incidents = db.query(Incident).filter(Incident.status == "Resolved").all()
    
    sim_state = db.query(SimulationState).first()
    scenario_name = sim_state.scenario_name if sim_state else "Baseline"
    
    pdf.set_font("helvetica", "", 10)
    pdf.multi_cell(0, 6, f"This diagnostic report assesses the operational integrity of the NetSage virtual enterprise network environment. The assessment was performed under the simulation scenario '{scenario_name}'.\n\n"
                          f"Currently, {healthy_devices} out of {total_devices} devices are reporting Healthy status. "
                          f"There are {len(open_incidents)} open active network incidents that require immediate operational review. "
                          f"{len(resolved_incidents)} historical incidents have been cataloged and resolved.")
    pdf.ln(5)
    
    # Device Health Grid
    pdf.set_fill_color(241, 245, 249)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, " 2. Device Status Matrix", fill=True, ln=True)
    pdf.ln(2)
    
    # Table Header
    pdf.set_font("helvetica", "B", 9)
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(30, 8, "Device Name", border=1, fill=True)
    pdf.cell(25, 8, "Type", border=1, fill=True)
    pdf.cell(35, 8, "IP Address", border=1, fill=True)
    pdf.cell(30, 8, "Health Status", border=1, fill=True)
    pdf.cell(35, 8, "CPU / Mem Usage", border=1, fill=True)
    pdf.cell(35, 8, "Last Checked", border=1, fill=True, ln=True)
    
    # Table Row Data
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("helvetica", "", 9)
    for dev in devices:
        pdf.cell(30, 8, dev.name, border=1)
        pdf.cell(25, 8, dev.type.capitalize(), border=1)
        pdf.cell(35, 8, dev.ip, border=1)
        
        # Color status
        if dev.status == "Healthy":
            pdf.set_text_color(22, 101, 52) # Dark Green
        elif dev.status == "Warning":
            pdf.set_text_color(180, 83, 9) # Dark Amber
        else:
            pdf.set_text_color(153, 27, 27) # Dark Red
            
        pdf.cell(30, 8, dev.status, border=1)
        pdf.set_text_color(0, 0, 0)
        
        pdf.cell(35, 8, f"{dev.cpu_usage:.1f}% / {dev.memory_usage:.1f}%", border=1)
        pdf.cell(35, 8, dev.last_checked.strftime("%H:%M:%S"), border=1, ln=True)
    pdf.ln(5)
    
    # Active Incidents & Root Causes
    pdf.set_fill_color(241, 245, 249)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, " 3. Active Incident Diagnostics & Recommendations", fill=True, ln=True)
    pdf.ln(2)
    
    if len(open_incidents) == 0:
        pdf.set_font("helvetica", "I", 10)
        pdf.cell(0, 10, "No active network faults or diagnostic incidents are open at this time.", ln=True)
    else:
        for inc in open_incidents:
            pdf.set_font("helvetica", "B", 10)
            pdf.set_fill_color(254, 242, 242) # Soft Red
            pdf.cell(0, 7, f"Incident {inc.incident_id} | {inc.device_name} | Severity: {inc.severity} (Confidence: {inc.confidence_score:.0f}%)", fill=True, ln=True)
            pdf.ln(1)
            
            pdf.set_font("helvetica", "B", 9)
            pdf.cell(25, 5, "Issue Type:")
            pdf.set_font("helvetica", "", 9)
            pdf.cell(0, 5, inc.issue, ln=True)
            
            pdf.set_font("helvetica", "B", 9)
            pdf.cell(25, 5, "Root Cause:")
            pdf.set_font("helvetica", "", 9)
            pdf.cell(0, 5, inc.root_cause, ln=True)
            
            # AI Advisor Details
            if inc.resolution_notes:
                try:
                    notes = json.loads(inc.resolution_notes)
                    
                    pdf.set_font("helvetica", "B", 9)
                    pdf.cell(0, 5, "AI Technical Advisor Analysis:", ln=True)
                    
                    pdf.set_font("helvetica", "", 9)
                    pdf.multi_cell(0, 5, f"Root Cause: {notes.get('root_cause_explanation')}\n"
                                          f"Impact Analysis: {notes.get('impact_analysis')}\n"
                                          f"Recommended Remediation: {notes.get('recommended_fix')}")
                    
                    pdf.set_font("helvetica", "B", 9)
                    pdf.cell(0, 5, "Step-by-Step Remediation CLI Commands:", ln=True)
                    pdf.set_font("courier", "", 8.5)
                    for step in notes.get("remediation_steps", []):
                        pdf.cell(5, 4, " -")
                        pdf.cell(0, 4, step, ln=True)
                        
                    pdf.set_font("helvetica", "B", 9)
                    pdf.cell(0, 5, "Validation Commands to Run:", ln=True)
                    pdf.set_font("courier", "", 8.5)
                    for cmd in notes.get("validation_commands", []):
                        pdf.cell(5, 4, " >")
                        pdf.cell(0, 4, cmd, ln=True)
                except Exception as e:
                    pdf.cell(0, 5, f"Remediation guidelines: {inc.resolution_notes}", ln=True)
            pdf.ln(3)
            
    # Save PDF
    pdf_path = os.path.join(REPORTS_DIR, "netsage_monthly_report.pdf")
    pdf.output(pdf_path)
    return pdf_path

def generate_csv_report(db: Session) -> str:
    csv_path = os.path.join(REPORTS_DIR, "netsage_incident_history.csv")
    incidents = db.query(Incident).order_by(Incident.timestamp.desc()).all()
    
    try:
        with open(csv_path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["Incident ID", "Timestamp", "Device", "Severity", "Issue Category / Root Cause", "Specific Diagnostic", "Confidence Score", "Status"])
            for inc in incidents:
                writer.writerow([
                    inc.incident_id,
                    inc.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
                    inc.device_name,
                    inc.severity,
                    inc.root_cause,
                    inc.issue,
                    f"{inc.confidence_score:.1f}%",
                    inc.status
                ])
    except Exception as e:
        print(f"Failed to generate CSV: {e}")
    return csv_path

def generate_html_report(db: Session) -> str:
    html_path = os.path.join(REPORTS_DIR, "netsage_executive_report.html")
    
    devices = db.query(Device).all()
    total_devices = len(devices)
    healthy_devices = len([d for d in devices if d.status == "Healthy"])
    critical_devices = len([d for d in devices if d.status == "Critical"])
    
    open_incidents = db.query(Incident).filter(Incident.status == "Open").all()
    all_incidents = db.query(Incident).order_by(Incident.timestamp.desc()).all()
    
    sim_state = db.query(SimulationState).first()
    scenario_name = sim_state.scenario_name if sim_state else "Baseline"
    
    device_rows = ""
    for dev in devices:
        status_color = "bg-green-950 text-green-400 border-green-800" if dev.status == "Healthy" else ("bg-red-950 text-red-400 border-red-800" if dev.status == "Critical" else "bg-yellow-950 text-yellow-400 border-yellow-800")
        device_rows += f"""
        <tr class="border-b border-slate-800 hover:bg-slate-900/50 transition-colors">
            <td class="px-6 py-4 font-semibold text-slate-200">{dev.name}</td>
            <td class="px-6 py-4 text-slate-400">{dev.type.upper()}</td>
            <td class="px-6 py-4 text-slate-400">{dev.ip}</td>
            <td class="px-6 py-4"><span class="px-2.5 py-0.5 rounded-full border text-xs font-semibold {status_color}">{dev.status}</span></td>
            <td class="px-6 py-4 text-slate-300 font-mono text-xs">{dev.cpu_usage:.1f}% / {dev.memory_usage:.1f}%</td>
            <td class="px-6 py-4 text-slate-400 text-xs">{dev.last_checked.strftime("%H:%M:%S")}</td>
        </tr>
        """
        
    incident_cards = ""
    if len(open_incidents) == 0:
        incident_cards = "<p class='text-slate-400 italic text-sm py-4'>No active network faults are open at this time.</p>"
    else:
        for inc in open_incidents:
            notes_html = ""
            if inc.resolution_notes:
                try:
                    notes = json.loads(inc.resolution_notes)
                    steps = "".join(f"<li class='mb-1'>{s}</li>" for s in notes.get("remediation_steps", []))
                    cmds = "".join(f"<div class='bg-slate-950/70 p-2 rounded text-rose-300 font-mono text-xs mb-1 border border-slate-800'>> {c}</div>" for c in notes.get("validation_commands", []))
                    notes_html = f"""
                    <div class="mt-4 border-t border-slate-800 pt-4 text-sm text-slate-400">
                        <p class="mb-2"><strong class="text-slate-300">Root Cause Detail:</strong> {notes.get('root_cause_explanation')}</p>
                        <p class="mb-2"><strong class="text-slate-300">Operational Impact:</strong> {notes.get('impact_analysis')}</p>
                        <p class="mb-2"><strong class="text-slate-300">Core Fix:</strong> {notes.get('recommended_fix')}</p>
                        
                        <div class="mt-3">
                            <strong class="text-slate-300 block mb-1">Execution Steps:</strong>
                            <ol class="list-decimal pl-5 text-xs text-slate-400 space-y-1">
                                {steps}
                            </ol>
                        </div>
                        <div class="mt-3">
                            <strong class="text-slate-300 block mb-1">Validation CLI Actions:</strong>
                            {cmds}
                        </div>
                    </div>
                    """
                except Exception:
                    notes_html = f"<p class='text-xs font-mono text-slate-400'>{inc.resolution_notes}</p>"
                    
            sev_color = "bg-rose-950/40 text-rose-400 border-rose-900/60" if inc.severity in ["Critical", "High"] else "bg-amber-950/40 text-amber-400 border-amber-900/60"
            incident_cards += f"""
            <div class="bg-slate-900/60 border border-slate-800/80 rounded-xl p-6 backdrop-blur-md mb-4 hover:border-slate-700/80 transition-all">
                <div class="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 pb-3 mb-3">
                    <div class="flex items-center gap-2">
                        <span class="text-xs px-2 py-0.5 rounded bg-slate-800 text-slate-300 border border-slate-700 font-mono font-semibold">{inc.incident_id}</span>
                        <h4 class="font-bold text-slate-200 text-lg">{inc.issue}</h4>
                    </div>
                    <div class="flex items-center gap-2">
                        <span class="text-xs px-2.5 py-0.5 border rounded-full font-semibold {sev_color}">{inc.severity}</span>
                        <span class="text-xs px-2 py-0.5 bg-blue-950/40 text-blue-400 border border-blue-900/50 rounded-full font-bold">Confidence: {inc.confidence_score:.0f}%</span>
                    </div>
                </div>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm mb-2 text-slate-400">
                    <div><strong class="text-slate-300">Device Target:</strong> <span class="font-mono text-xs">{inc.device_name}</span></div>
                    <div><strong class="text-slate-300">Timeline Trigger:</strong> {inc.timestamp.strftime("%Y-%m-%d %H:%M:%S")}</div>
                </div>
                {notes_html}
            </div>
            """
            
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NetSage Diagnostics Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-slate-100 min-h-screen py-10 font-sans">
    <div class="max-w-5xl mx-auto px-4">
        <!-- Brand Header -->
        <header class="flex items-center justify-between border-b border-slate-800 pb-6 mb-8">
            <div>
                <h1 class="text-3xl font-extrabold tracking-wider bg-gradient-to-r from-blue-400 to-indigo-500 bg-clip-text text-transparent">NETSAGE EXECUTIVE ASSESSMENT</h1>
                <p class="text-xs text-slate-400 uppercase mt-1 tracking-widest font-semibold font-mono">Automated Network Reliability Engine Logs</p>
            </div>
            <div class="text-right">
                <span class="text-xs bg-slate-900 border border-slate-800 px-3 py-1.5 rounded-lg text-slate-400 font-mono">Run Scenario: {scenario_name}</span>
            </div>
        </header>

        <!-- Stats Overview Grid -->
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
            <div class="bg-slate-900/50 border border-slate-800 p-5 rounded-xl">
                <p class="text-xs text-slate-500 uppercase font-bold tracking-wider mb-1">Total Monitored Nodes</p>
                <p class="text-3xl font-bold font-mono text-slate-200">{total_devices}</p>
            </div>
            <div class="bg-slate-900/50 border border-slate-800 p-5 rounded-xl">
                <p class="text-xs text-slate-500 uppercase font-bold tracking-wider mb-1">Healthy Baseline</p>
                <p class="text-3xl font-bold font-mono text-green-400">{healthy_devices}</p>
            </div>
            <div class="bg-slate-900/50 border border-slate-800 p-5 rounded-xl">
                <p class="text-xs text-slate-500 uppercase font-bold tracking-wider mb-1">Critical Outages</p>
                <p class="text-3xl font-bold font-mono text-rose-500">{critical_devices}</p>
            </div>
            <div class="bg-slate-900/50 border border-slate-800 p-5 rounded-xl">
                <p class="text-xs text-slate-500 uppercase font-bold tracking-wider mb-1">Active Alerts</p>
                <p class="text-3xl font-bold font-mono text-amber-500">{len(open_incidents)}</p>
            </div>
        </div>

        <!-- Section 1: Device Assessment -->
        <section class="mb-10">
            <h3 class="text-xl font-bold text-slate-200 mb-4 flex items-center gap-2">
                <span class="h-2 w-2 rounded-full bg-blue-400"></span> 1. Device Operational Matrix
            </h3>
            <div class="overflow-x-auto rounded-xl border border-slate-800/80 bg-slate-900/20 backdrop-blur-sm">
                <table class="w-full border-collapse text-left text-sm">
                    <thead>
                        <tr class="bg-slate-900/80 border-b border-slate-800 text-slate-400 font-semibold text-xs uppercase tracking-wider">
                            <th class="px-6 py-3.5">Device Name</th>
                            <th class="px-6 py-3.5">Type</th>
                            <th class="px-6 py-3.5">IP Address</th>
                            <th class="px-6 py-3.5">Health</th>
                            <th class="px-6 py-3.5">CPU / MEM</th>
                            <th class="px-6 py-3.5">Timestamp</th>
                        </tr>
                    </thead>
                    <tbody>
                        {device_rows}
                    </tbody>
                </table>
            </div>
        </section>

        <!-- Section 2: Active Root Causes -->
        <section class="mb-10">
            <h3 class="text-xl font-bold text-slate-200 mb-4 flex items-center gap-2">
                <span class="h-2 w-2 rounded-full bg-blue-400"></span> 2. Active Incidents & Root Cause Diagnosis
            </h3>
            {incident_cards}
        </section>
        
        <footer class="border-t border-slate-800/80 pt-6 mt-16 text-center text-xs text-slate-500">
            <p>Report generated dynamically by NetSage NRE Platform. Confidential operational diagnostics.</p>
        </footer>
    </div>
</body>
</html>
"""
    try:
        with open(html_path, "w") as f:
            f.write(html_content)
    except Exception as e:
        print(f"Failed to generate HTML: {e}")
    return html_path
